# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-01 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_proposalformsubmission_proposalformsubmissionfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
