# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-02 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='paris@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
