# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='key_fingerprint',
            field=models.CharField(default='0D7C84CC02EA2DFCE68C356A6E10FA72C1896198', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='key_id',
            field=models.CharField(default='6E10FA72C1896198', max_length=255),
        ),
    ]
