# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-02 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_auto_20161002_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalformsubmission',
            name='plain_txt',
            field=models.CharField(max_length=65535, null=True),
        ),
        migrations.AddField(
            model_name='proposalformsubmission',
            name='plain_txt_signed',
            field=models.CharField(max_length=65535, null=True),
        ),
    ]
